.\"
.\" Manual for kextlogd
.\"
.\" Created 190301+0800 lynnl
.\"
.Dd March 01, 2018       \" DATE
.Dt KEXTLOGD 1           \" Program name and manual section number
.Os Darwin
.Sh NAME                 \" Section Header - required - don't modify
.Nm kextlogd
.\" Use .Nm macro to designate other names for the documented program.
.Nd Kernel extension log recorder
.Sh SYNOPSIS             \" Section Header - required - don't modify
.Nm
.Op Fl o Ar file
.Op Fl x Ar number
.Op Fl n Ar number
.Op Fl ifcvh
.Op Fl b
.Ar name                 \" Underlined argument - use .Ar anywhere to underline
.Sh DESCRIPTION          \" Section Header - required - don't modify
The
.Nm
utility used to record kernel extension log, it can be used either for a generic kext or an IOKit kext.
.Pp                      \" Inserts a space
The following options are available:
.Bl -tag -width -indent
.It Ar name
Denoted the kext bundle name.
.It Fl b , -bundle-id
The \fIname\fR is a kext bundle identifier instead.
.It Fl o , -output Ar file
Log all kext messages to \fIfile\fR.
Default is stdout.
.It Fl x , -max-size Ar number
Single log maximum file size in bytes, when reached maximum size \fInumber\fR,
.Nm
will either rewind current log file(if any), or roll the log and open a new file for logging.
.Pp
Default value is 0, it means no limit.
.It Fl n, -rolling-count Ar number
Maximum rolling count, when a log reached single maximum size, it will roll to .1, .2, ..., .\fInumber\fR.
.Pp
Default value is 0, it means in-place(no) rolling.
.It Fl i , -ignore-case
Capture any messages contains keywords \fIname\fR(case-insensitive), imply \fB--fuzzy\fR.
.Pp
(available on macOS >= 10.12)
.It Fl f, -fuzzy
Capture any messages contains keywords \fIname\fR.
.Pp
(available on macOS >= 10.12)
.It Fl c, -color
Hightlight messages of different types, only effective for TTY logging.
.Pp
(available on macOS >= 10.13)
.It Fl v, -version
Print
.Nm
version
.It Fl h, -help
Print
.Nm
help
.El                      \" Ends the list
.Sh CAVEATS
For macOS <= 10.10,
.Nm
acts as if \fB-f\fR(\fB--fuzzy\fR) option turned on by default.
.Sh SEE ALSO
.\" List links in ascending order by section, alphabetically within a section.
.\" Please do not reference files that do not exist without filing a bug report
.Xr log 1 ,
.Xr syslog 1 ,
.Xr kext_logging 8
